package com.wadpam.blood.dao;

/**
 * Business Methods interface for entity DDonor.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-11T13:58:37.469+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DDonorDao extends GeneratedDDonorDao {

	// TODO: declare your Business Methods here
	
}
