package com.wadpam.blood.dao;

/**
 * Implementation of Business Methods related to entity DDonor.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-11T13:58:37.469+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DDonorDaoBean 
	extends GeneratedDDonorDaoImpl
		implements DDonorDao 
{

	// TODO: implement your Business Methods here

}
