package com.wadpam.donor.dao;

/**
 * Implementation of Business Methods related to entity DDonation.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-25T17:21:16.603+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DDonationDaoBean 
	extends GeneratedDDonationDaoImpl
		implements DDonationDao 
{

	// TODO: implement your Business Methods here

}
